python create_memory_usage.py -n 6 --samples 100;
pkill -f python*;
python create_memory_usage.py -n 7 --samples 100;
pkill -f python*;
python create_memory_usage.py -n 8 --samples 100;
pkill -f python*;
python create_memory_usage.py -n 9 --samples 100;
pkill -f python*;
python create_memory_usage.py -n 10 --samples 100;
pkill -f python*;
python create_memory_usage.py -n 11 --samples 100;
pkill -f python*;
python create_memory_usage.py -n 12 --samples 100;
pkill -f python*;