python3 main.py -n 6 7 8 --delete -vv -s S --subt_extr 0;
python3 main.py -n 6 7 8 --delete -vv -s S --subt_extr 1;
python3 main.py -n 6 7 8 --delete -vv -s S --subt_extr 2;
python3 main.py -n 6 7 8 --delete -vv -s S --subt_extr 3;
python3 main.py -n 6 7 8 --delete -vv -s S --subt_extr 4;
python3 main.py -n 6 7 8 --delete -vv -s S --subt_extr 5;
python3 main.py -n 9 --delete -vv -s S --subt_extr 0;
python3 main.py -n 9 --delete -vv -s S --subt_extr 1;
python3 main.py -n 9 --delete -vv -s S --subt_extr 2;
python3 main.py -n 9 --delete -vv -s S --subt_extr 3;
python3 main.py -n 9 --delete -vv -s S --subt_extr 4;
python3 main.py -n 9 --delete -vv -s S --subt_extr 5;
python3 main.py -n 10 --delete -vv -s S --subt_extr 0;
python3 main.py -n 10 --delete -vv -s S --subt_extr 1;
python3 main.py -n 10 --delete -vv -s S --subt_extr 2;
python3 main.py -n 10 --delete -vv -s S --subt_extr 3;
python3 main.py -n 10 --delete -vv -s S --subt_extr 4;
python3 main.py -n 10 --delete -vv -s S --subt_extr 5;
